# Generated by Django 5.2.3 on 2025-06-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business/'),
        ),
    ]
