# Generated by Django 5.2.3 on 2025-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
