# Generated by Django 5.2.3 on 2025-06-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_businesscategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregion',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.district'),
        ),
        migrations.AlterField(
            model_name='userregion',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.region'),
        ),
    ]
